spring:
  application:
    name: cloudmall-cart
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: nacos
        password: nacos
        namespace: f64498e5-740a-4dac-972d-22597d7dc2c1
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: nacos
        password: nacos
        namespace: f64498e5-740a-4dac-972d-22597d7dc2c1
        enabled: false
  data:
    redis:
      host: ${DB_HOST:localhost}
      password: ${DB_PASSWORD:123456}
  session:
    redis:
      namespace: cloudmall:session
logging:
  level:
    root: info
    com.rainer.cloudmall: debug
server:
  port: 21000
  servlet:
    session:
      timeout: 360m